In [35]:
#importing dataset
import pandas as pd
import numpy as np

customers = pd.read_csv('customers_dataset.csv',
                 dtype={'customer_zip_code_prefix': str},
                 quotechar='"')
print(customers)

                            customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

      customer_zip_code_prefix          customer_city customer_state
0                        14409                 franca             SP
1                        09790  sao bernardo do campo             SP
2                        01151              sao paulo             SP
3                        08775        mogi das cruzes             SP
4                        13056               campinas             SP
...                        ...                    ...            ...
99436                    03937              sao paulo             SP
99437                    06764        taboao da serra             SP
99438                    60115              fortaleza             CE
99439                    92120                 canoas             RS
99440                    06703                  cotia             SP

[99441 rows x 5 columns]

In [36]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [37]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [38]:
customers.describe()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441,99441,99441
unique,99441,96096,14994,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,22790,sao paulo,SP
freq,1,17,142,15540,41746

In [39]:
#checking null values
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [40]:
#checking colums
print(customers.columns)

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [41]:
#deleting spaces and replacing with lower case
customers['customer_city'] = customers['customer_city'].str.lower().str.strip()
customers['customer_state'] = customers['customer_state'].str.upper().str.strip()
print(customers['customer_state'].unique())

['SP' 'SC' 'MG' 'PR' 'RJ' 'RS' 'PA' 'GO' 'ES' 'BA' 'MA' 'MS' 'CE' 'DF'
 'RN' 'PE' 'MT' 'AM' 'AP' 'AL' 'RO' 'PB' 'TO' 'PI' 'AC' 'SE' 'RR']

In [42]:
#checking to duplicates
print(customers.duplicated().sum())

0

In [43]:
#zip_code column is string value and has 5 symbols
customers['customer_zip_code_prefix'] = customers['customer_zip_code_prefix'].astype(str).str.zfill(5)

In [44]:
# create new column customer_region
region_map = {
    'SP': 'Sudeste', 'RJ': 'Sudeste', 'MG': 'Sudeste', 'ES': 'Sudeste',
    'PR': 'Sul', 'RS': 'Sul', 'SC': 'Sul',
    'BA': 'Nordeste', 'PE': 'Nordeste', 'CE': 'Nordeste', 'MA': 'Nordeste',
    'PA': 'Norte', 'AM': 'Norte', 'AC': 'Norte', 'RO': 'Norte',
    'GO': 'Centro-Oeste', 'DF': 'Centro-Oeste', 'MT': 'Centro-Oeste', 'MS': 'Centro-Oeste'}

customers['customer_region'] = customers['customer_state'].map(region_map)

In [45]:
customers[['customer_region', 'customer_state']].head(10)

  customer_region customer_state
0         Sudeste             SP
1         Sudeste             SP
2         Sudeste             SP
3         Sudeste             SP
4         Sudeste             SP
5             Sul             SC
6         Sudeste             SP
7         Sudeste             MG
8             Sul             PR
9         Sudeste             MG

In [46]:
#deleting spaces and '' in the rows
customers['customer_city'] = customers['customer_city'].str.replace('"', '', regex=False)

In [47]:
#uploading clean dataset
customers.to_csv('customers_clean.csv', index=False, encoding='utf-8-sig')

In [48]:
#importing dataset
orders = pd.read_csv('orders_dataset.csv')
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [49]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [50]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [51]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [52]:
#make sure that colmns with date in type datetime
date_cols = ['order_purchase_timestamp', 'order_approved_at',
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date']
for col in date_cols:
  orders[col] = pd.to_datetime(orders[col], format = '%Y-%m-%d %H:%M:%S', errors = 'coerce')

In [53]:
#orders with delivered status has null values
orders[orders['order_status'] == 'delivered'][['order_delivered_customer_date']].isnull().sum()

order_delivered_customer_date    8
dtype: int64

In [54]:
orders.dropna(subset =['order_delivered_customer_date'])

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [55]:
# Удаляем заказы, у которых дата одобрения раньше даты покупки
orders = orders[orders['order_approved_at'] >= orders['order_purchase_timestamp']]

# Удаляем заказы, у которых доставка раньше покупки
orders = orders[orders['order_delivered_customer_date'] >= orders['order_purchase_timestamp']]

# Аналогично для передачи перевозчику
orders = orders[orders['order_delivered_carrier_date'] >= orders['order_purchase_timestamp']]

In [56]:
#time between
orders['days_to_approve'] = (orders['order_approved_at'] - orders['order_purchase_timestamp']).dt.total_seconds() / 3600 / 24
orders['days_to_carrier'] = (orders['order_delivered_carrier_date'] - orders['order_purchase_timestamp']).dt.total_seconds() / 3600 / 24
orders['days_in_transit'] = (orders['order_delivered_customer_date'] - orders['order_delivered_carrier_date']).dt.total_seconds() / 3600 / 24
orders['total_delivery_time'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.total_seconds() / 3600 / 24

#late and early delivered
orders['delivered_late_days'] = (orders['order_delivered_customer_date'] - orders['order_estimated_delivery_date']).dt.total_seconds() / 3600 / 24
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,days_to_approve,days_to_carrier,days_in_transit,total_delivery_time,delivered_late_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0.007431,2.373924,6.062650,8.436574,-7.107488
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.279745,1.742627,12.039410,13.782037,-5.355729
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0.011505,0.216100,9.178113,9.394213,-17.245498
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0.012419,3.758252,9.450498,13.208750,-12.980069
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0.042940,0.936053,1.937824,2.873877,-9.238171
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,0.000000,1.058310,7.159699,8.218009,-10.369433
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,0.008090,1.433148,20.760579,22.193727,-1.265324
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,0.012187,1.253970,23.605451,24.859421,-5.524803
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,0.005486,3.754583,13.331840,17.086424,-20.018819
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,0.599282,1.051725,6.622581,7.674306,-17.452431

In [57]:
#max days to deliver 209
print(max(orders['total_delivery_time']))

orders['delivery_days'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.days
print(orders['delivery_days'])

#avg delivery days
avg = orders['delivery_days'].mean()
print(avg)

209.62861111111113
0         8
1        13
2         9
3        13
4         2
         ..
99436     8
99437    22
99438    24
99439    17
99440     7
Name: delivery_days, Length: 96296, dtype: int64
12.102236853036471

In [58]:
#uploading clean dataset
orders.to_csv('orders_clean.csv', index=False, encoding='utf-8-sig')

In [59]:
#importing dataset and deleting not needed columns
items = pd.read_csv('order_items_dataset.csv', delimiter=',', encoding='utf-8')
items = items.drop(columns =['freight_value'])
items = items.drop(columns =['seller_id'])
print(items)

                                order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1
1       00018f77f2f0320c557190d7a144bdd3              1
2       000229ec398224ef6ca0657da4fc703e              1
3       00024acbcdf0a6daa1e931b038114c75              1
4       00042b26cf59d7ce69dfabb4e55b4fd9              1
...                                  ...            ...
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id  shipping_limit_date   price
0       4244733e06e7ecb4970a6e2683c13e61  2017-09-19 09:45:35   58.90
1       e5f2d52b802189ee658865ca93d83a8f  2017-05-03 11:05:13  239.90
2       c777355d18b72b67abbeef9df44fd0fd  2018-01-18 14:48:30  199.00
3       7634da152a4610f1595efa32f14722fc  2018-08-15 10:10:18   12.99
4       ac6c3623068f30de03045865e4e10089  2017-02-13 13:57:51  199.90
...                                  ...                  ...     ...
112645  4aa6014eceb682077f9dc4bffebc05b0  2018-05-02 04:11:01  299.99
112646  32e07fd915822b0765e448c4dd74c828  2018-07-20 04:31:48  350.00
112647  72a30483855e2eafc67aee5dc2560482  2017-10-30 17:14:25   99.90
112648  9c422a519119dcad7575db5af1ba540e  2017-08-21 00:04:32   55.99
112649  350688d9dc1e75ff97be326363655e01  2018-06-12 17:10:13   43.00

[112650 rows x 5 columns]

In [60]:
#basic info about dataset
print(type(items))
print(items.head())
print(items.info())
print(items.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id  shipping_limit_date   price
0  4244733e06e7ecb4970a6e2683c13e61  2017-09-19 09:45:35   58.90
1  e5f2d52b802189ee658865ca93d83a8f  2017-05-03 11:05:13  239.90
2  c777355d18b72b67abbeef9df44fd0fd  2018-01-18 14:48:30  199.00
3  7634da152a4610f1595efa32f14722fc  2018-08-15 10:10:18   12.99
4  ac6c3623068f30de03045865e4e10089  2017-02-13 13:57:51  199.90
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   shipping_limit_date  112650 non-null  object
 4   price                112650 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.3+ MB
None
order_id               0
order_item_id          0
product_id             0
shipping_limit_date    0
price                  0
dtype: int64

In [61]:
#uploading csv file
items.to_csv('items_clean.csv', index = False, encoding = 'utf-8-sig')

In [63]:
#importing next dataset
payments = pd.read_csv('order_payments_dataset.csv')
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [64]:
#checking unique values
payments['payment_sequential'].unique()
payments['payment_installments'].unique()

array([ 8,  1,  2,  3,  6,  5,  4, 10,  7, 12,  9, 13, 15, 24, 11, 18, 14,
       20, 21, 17, 22,  0, 16, 23])

In [65]:
payments = payments.drop(columns = ['payment_sequential'])
print(payments)

                                order_id payment_type  payment_installments  \
0       b81ef226f3fe1789b1e8b2acac839d17  credit_card                     8
1       a9810da82917af2d9aefd1278f1dcfa0  credit_card                     1
2       25e8ea4e93396b6fa0d3dd708e76c1bd  credit_card                     1
3       ba78997921bbcdc1373bb41e913ab953  credit_card                     8
4       42fdf880ba16b47b59251dd489d4441a  credit_card                     2
...                                  ...          ...                   ...
103881  0406037ad97740d563a178ecc7a2075c       boleto                     1
103882  7b905861d7c825891d6347454ea7863f  credit_card                     2
103883  32609bbb3dd69b3c066a6860554a77bf  credit_card                     1
103884  b8b61059626efa996a60be9bb9320e10  credit_card                     5
103885  28bbae6599b09d39ca406b747b6632b1       boleto                     1

        payment_value
0               99.33
1               24.39
2               65.71
3              107.78
4              128.45
...               ...
103881         363.31
103882          96.80
103883          47.77
103884         369.54
103885         191.58

[103886 rows x 4 columns]

In [66]:
#uploading csv file
payments.to_csv('payments_clean.csv', index = False, encoding = 'utf-8-sig')

In [72]:
#importing next dataset
products = pd.read_csv('products_dataset.csv', sep = ',')
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [73]:
#deleting not needed columns
products = products.drop(columns = 'product_name_lenght')
products = products.drop(columns = 'product_description_lenght')
products = products.drop(columns = 'product_photos_qty')
print(products)

                             product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
0                  14.0
1                  20.0
2                  15.0
3                  26.0
4                  13.0
...                 ...
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

[32951 rows x 6 columns]

In [74]:
#deleting null values
print(products.isnull().sum())
products = products.dropna(subset = 'product_category_name')
products = products.dropna(subset = 'product_weight_g')
products = products.dropna(subset = 'product_length_cm')
products = products.dropna(subset = 'product_height_cm')
products = products.dropna(subset = 'product_width_cm')

print(products.isnull().sum())

product_id                 0
product_category_name    610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64
product_id               0
product_category_name    0
product_weight_g         0
product_length_cm        0
product_height_cm        0
product_width_cm         0
dtype: int64

In [75]:
#info of dataset
products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32340 non-null  object
 1   product_category_name  32340 non-null  object
 2   product_weight_g       32340 non-null  float64
 3   product_length_cm      32340 non-null  float64
 4   product_height_cm      32340 non-null  float64
 5   product_width_cm       32340 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.7+ MB

In [76]:
#uploading file
products.to_csv('products_clean.csv', index = False, encoding = 'utf-8-sig')